name: ♾️ Continuous Integration

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🔬 Lint
        run: pnpm lint

      - name: 🧪 Test
        run: pnpm test
